#!/usr/bin/env bash

COMPUTER=$((1 + RANDOM % 50))

while true; do
  read -p "Pick a number between 1 and 50: " GUESS
  if [[ $GUESS -lt $COMPUTER ]]; then
    echo "Too low"
    continue
  elif [[ $GUESS -gt $COMPUTER ]]; then
    echo "Too high"
    continue
  else
    echo "You GOT IT!"
    exit 0
  fi
done
